apiVersion: v1
kind: ConfigMap
metadata:
  name: linkup-backend-config
data:
  RABBITMQ_HOST: "linkup-rabbitmq"
  RABBITMQ_PORT: "5672"
  RABBITMQ_USER: "guest"
  AWS_REGION: "eu-central-1"
  S3_BUCKET_NAME: "linkup-files"
  FRONTEND_URL: "https://linkup.co.il"