apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: linkup

resources:
  - configmap.yaml
  - postgres.yaml
  - redis.yaml
  - rabbitmq.yaml

commonLabels:
  app.kubernetes.io/component: infra
