apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkup-rabbitmq
  labels:
    app: linkup-rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: linkup-rabbitmq
  template:
    metadata:
      labels:
        app: linkup-rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3-management
          env:
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                configMapKeyRef:
                  name: linkup-rabbitmq-config
                  key: user
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: linkup-rabbitmq-secret
                  key: password
          ports:
            - containerPort: 5672
              name: amqp
            - containerPort: 15672
              name: management
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: linkup-rabbitmq
  labels:
    app: linkup-rabbitmq
spec:
  type: ClusterIP
  ports:
    - port: 5672
      targetPort: 5672
      protocol: TCP
      name: amqp
    - port: 15672
      targetPort: 15672
      protocol: TCP
      name: management
  selector:
    app: linkup-rabbitmq
