apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkup-redis
  labels:
    app: linkup-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: linkup-redis
  template:
    metadata:
      labels:
        app: linkup-redis
    spec:
      containers:
        - name: redis
          image: redis/redis-stack:7.2.0-v10
          command:
            - sh
            - -c
            - "redis-server --requirepass $$REDIS_PASSWORD"
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: linkup-redis-secret
                  key: password
          ports:
            - containerPort: 6379
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: linkup-redis
  labels:
    app: linkup-redis
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
      name: redis
  selector:
    app: linkup-redis
