apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - ../infra
  - ../email-renderer
  - ../backend
  - ../frontend
  - ../chat-ws
  - ../worker

commonLabels:
  app.kubernetes.io/part-of: linkup
